import type { Metadata } from "next";
import { type ReactNode } from "react";
import Navbar from "./(components)/Navbar";
import { Toaster } from "@/components/ui/toaster";


export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default async function GameLayout(props: { children: ReactNode }) {


  return (
    <main>
      <Navbar />
      {props.children}
      <Toaster />

    </main>
  );
}
